package it.polimi.tiw.auctions.beans;

import java.io.Serializable;

/**
 * Represents a User entity, mirroring the 'user' table in the database.
 * This record holds all information pertaining to a user, such as credentials,
 * personal details, and shipping address.
 * The primary key is 'id' (auto-incremented by the database).
 * A unique constraint is expected on 'username'.
 * It implements {@link Serializable} for session management or other serialization needs.
 */
public record User(
    int id,
    String username,
    String password,//no hash for simplicity
    String name,
    String surname,
    String shippingAddress
) implements Serializable {
    private static final long serialVersionUID = 1L; // Unique ID for serialization.

    /**
     * Compact constructor for the {@link User} record.
     * This constructor performs basic validation on the user's attributes.
     * The database typically handles auto-increment for the 'id'.
     * Uniqueness of 'username' should be checked by a Data Access Object (DAO) before insertion.
     *
     * @param id The unique identifier of the user.
     * @param username The user's chosen username. Cannot be null or blank.
     * @param password The user's password. Cannot be null or blank.
     * @param name The user's first name. Cannot be null or blank.
     * @param surname The user's last name. Cannot be null or blank.
     * @param shippingAddress The user's shipping address. Cannot be null or blank.
     * @throws IllegalArgumentException if any of the validation rules are violated.
     */
    public User {
        // Validate that the username is not null or blank.
        if (username == null || username.isBlank()) {
            throw new IllegalArgumentException("Username cannot be null or blank.");
        }
        // Validate that the password is not null or blank.
        if (password == null || password.isBlank()) {
            throw new IllegalArgumentException("Password cannot be null or blank.");
        }
        // Validate that the first name is not null or blank.
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("Name cannot be null or blank.");
        }
        // Validate that the surname is not null or blank.
        if (surname == null || surname.isBlank()) {
            throw new IllegalArgumentException("Surname cannot be null or blank.");
        }
        // Validate that the shipping address is not null or blank.
        if (shippingAddress == null || shippingAddress.isBlank()) {
            throw new IllegalArgumentException("Shipping address cannot be null or blank.");
        }
    }

    /**
     * Convenience static factory method to create a {@link User} instance for insertion into the database,
     * typically when the ID is not yet known (as it will be auto-generated by the database).
     *
     * @param username The user's chosen username.
     * @param password The user's password.
     * @param name The user's first name.
     * @param surname The user's last name.
     * @param shippingAddress The user's shipping address.
     * @return A new {@link User} object configured for database insertion.
     */
    public static User createUserForInsert(String username, String password, String name, String surname, String shippingAddress) {
        // Create and return a new User object.
        // The ID is set to 0 as a convention, indicating it's unassigned; the database will generate it.
        return new User(0, username, password, name, surname, shippingAddress);
    }
}