package it.polimi.tiw.auctions.beans;

import java.io.Serializable;

/**
 * Represents a User entity in the online auction system, corresponding to the 'user' table.
 * This record holds all information pertaining to a user, including credentials,
 * personal details (name, surname), and shipping address.
 * The 'id' serves as the primary key and is typically auto-incremented by the database.
 * 'username' is expected to have a unique constraint.
 * This class implements {@link Serializable}, making its instances eligible for
 * session storage or other forms of serialization.
 */
public record User(
    int id,
    String username,
    String password, //not hashed for simplicity
    String name,
    String surname,
    String shippingAddress
) implements Serializable {
    private static final long serialVersionUID = 1L; // Unique ID for serialization.

    /**
     * Compact constructor for the {@link User} record.
     * This constructor performs validation on the user's attributes upon instantiation.
     *
     * @param id The unique identifier of the user.
     * @param username The user's chosen username. Cannot be null or blank.
     * @param password The user's password. Cannot be null or blank.
     * @param name The user's first name. Cannot be null or blank.
     * @param surname The user's last name. Cannot be null or blank.
     * @param shippingAddress The user's shipping address. Cannot be null or blank.
     * @throws IllegalArgumentException if any validation rule is violated.
     */
    public User {
        // Validate username: must not be null or blank.
        if (username == null || username.isBlank()) {
            throw new IllegalArgumentException("Username cannot be null or blank.");
        }
        // Validate password: must not be null or blank.
        if (password == null || password.isBlank()) {
            throw new IllegalArgumentException("Password cannot be null or blank.");
        }
        // Validate name: must not be null or blank.
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("Name cannot be null or blank.");
        }
        // Validate surname: must not be null or blank.
        if (surname == null || surname.isBlank()) {
            throw new IllegalArgumentException("Surname cannot be null or blank.");
        }
        // Validate shippingAddress: must not be null or blank.
        if (shippingAddress == null || shippingAddress.isBlank()) {
            throw new IllegalArgumentException("Shipping address cannot be null or blank.");
        }
    }

    /**
     * Static factory method to create a {@link User} instance, typically for new user registration
     * where the ID will be auto-generated by the database.
     *
     * @param username The username for the new user.
     * @param password The password for the new user.
     * @param name The first name of the new user.
     * @param surname The last name of the new user.
     * @param shippingAddress The shipping address for the new user.
     * @return A new {@link User} object, configured for database insertion.
     */
    public static User createUserForInsert(String username, String password, String name, String surname, String shippingAddress) {
        // Create a new User instance with ID 0 (or another convention indicating a new record).
        return new User(0, username, password, name, surname, shippingAddress);
    }
}